apiVersion: v1
kind: Secret
metadata:
    name: installconfig
    namespace: replace-me
    labels:
        cluster.open-cluster-management.io/backup: ""
data:
    install-config.yaml: ENC[AES256_GCM,data:erYQTlqH0uYAjfez4gZt8yIIVlX99DJkRYIqcg2ofitdmx/m5x+TNkA9KT7Sa70p0fjqg3vvjlYYg7LMAWxEeVnAOi4wtRFOAL+AlqqMt6fSJNXIuUPtv7VLQqJmDFTbzWwEGDxWHrlRUx281zgmrbMWfovWELp7tSe4lrRdceHxew4bSjGKXzVpgzn67kGpsvvGRlWlnJJHVU+uRAFcfU1wx7abVPhL6RGxOqIgss4XHWkxZioOiTviBC+MQnKRSiw+CibqcamGkf8k1OgROPHGBU2tKoOLa/ZWa8161sOLPSWMkiHDlD2IaKf8eTaVwExP/k9HCHFLt8wDa8YJzpbuL5N1FHY3M4ZTGjw20UewP8JdKI2r8QxuipmiZA7RUeez+5L/qdkJLUdrOCz0gP6/TPPfTIJSdvSrK2dS60h2HIO+jo5o4dgcG3FpZFSPCq/Iy4lGDju21pss6b4364rJ7En4em8kEQ0/EROBLyxK0E+R5mSl/JwT/3qTlkz0foqpuAknyq7fTF7StmvPZN5ZU9OR6RSXEmqQOBHVF+bYGTywiP11eX+uT6ayphU1ZND+QDjLZ0FTvvQlPMwfC95y01uathkcSMmMeCEaPEvW0n1s/9uwUGeYLar7NlAmJLb9FsLj8QgbObpP6azuUSPDifEpWyA5GN3A5Wn3FU4K2gX3bDr8R3zhJJ3jHMeFa63blMTgTtSKTvuOLucStWVImUsj1RCcz/8Fg3pA3K9/nzZKUgzwJoJ0iYSiTyKYA0kbSxhEAv348wMZ2kcxMoyJ8mK5VsU7Zt08RR1dsAZ7kcaX/xnd1IV60BvAbur2QoYtUt7bYln+7SEh9a6oQ+gySPQcvTKBzq6ocon4s9looWTdUNEuSnvvlYzS0AvU5hJ+cREvBmYzRHZ2x7+rehq7HNzB1keX9t1ZoElfm7MT4ox+svKYCihiGzJhONgA3Ge/uhmbMJS/Nbpleb7EKbFfhdK7E7ll2PdjPqDlJsfepQICQ8s9xCYpeD/A8cROaxTZpw144biJDlq878tKjZlitP/OrvbEz6NvRH8NvsMxWPAgIf3uGIqAmMkZuhwbYArTVLmdH5tGa64WMW3O14vofXNpb6CeaeOff/QFl3PnKYRZPqViaKwdZl9OTF/PGXOirqBVFURYb/T/MXlfLgIacUuIXe7BtTj3LjpMiKsUzfcUHwtrwhEJi8Bg1IGRg9zah0TsThdkn0rSDJ3TBM4mk91eM6hG1dnkI4pK1FeqiXnFYMwnFAOzhQc7MHeUIhMHFv99QfsIQ7qglj8vVfRDTrwwupNFgFjxvxmK8zliloQshFrY5DFaY6QcFGGyY2lYVasWxl85KLtezAtcsBiUJhXQDaFxpxvlUHLu7al36I+RqYW/c1xoSRFhrN4i3ASz03o+9ekRTPYThREKfiYI+ou0xKqrDdhprgzzvBk23AUaOTdtT2tPFZ1F8duv+XavewsfbvRFIaiWYLaf0CEWwPnCRsioeABTztp8qDzcTYXfvD0iYhjgAM3AC9KX0TbVk6FVyua4pH9/qKq3607xwnuCJNp/d8aLFaPDQhhqFVeDtK4cNtc9AqQUimA193IQGOpQf9LZMG4IP5VJT+rdRFF6lHBzeaAlTJhnQ4coJbCIRJTfvazzx/ySWTZ4kJ7EiscSmlv5oUwk72vuIepgHmTF4fgpHL9Oxj9nUQJ/QXuTXgii5hPKgpfk55hFEVWskvdXwn4U8df9ijfLsCBWZHUMz3RXkH/q3Cj1MfdwgF3J8t3zNrFbzt8YvtUX7EkUFSWadaPlETnR3wQmdiBe3Metr7D6rAE8W/jkz6tLzlUeC/51kRHr3h72P0zww7721LEoLsyx9OhwpJUTPiPixDlN53h2h5WrX5dePL2GNl3jvSXOlkfZxj/Oxa7PrVkbBXIMBmkrRuJWUHmZ/RwcvZJxpOuKBz5m/vQfUt0Hh4ucMILP7e7GcCslWr/tYBnCwbifVRSzks9+3X4fmg==,iv:Zxkzxhet5UPNBReHpmsd7rm1nR3umY1sKEwCRQyPB/Q=,tag:k1Vf5Lo3j9z7onTIHRdaSw==,type:str]
sops:
    lastmodified: "2026-04-09T18:29:09Z"
    mac: ENC[AES256_GCM,data:RkBAqoP7rwezLvMoTb0SOO9XiInq4praIEwMfJbSssTSOGyS43j+mSDcXATFZ0rxEsO5bKHxFO9m/JCoN1bEK4NKW0nVHg2LcAvmVsFzok3MXQZpKom7b5h5r6c6IE8UEXpSRQyowYxmxRZn85JWDHBg06e2040w855NXafEG9M=,iv:4RVpwk7lR2v2c9eFryGmNeLlyIC4u6fc0l70ngs20c4=,tag:lj75OpOuGOhKqqLfh2Z7dg==,type:str]
    pgp:
        - created_at: "2026-04-09T18:29:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAoWFcqiX/geZgwgezli/O3Uom+xTnBw7mLHJkxXhBEh4w
            c1Tz9iDrbkNbG6p+GJZzl1p+M62Ks+dY4nyDqyl6WMRR4ptobYVorxqZzntRi2YQ
            0l4BqbRc1IW2uQzsFIO/B+Fu2J2fBqB+fjEqeZHUt3MdRKu9LS+55ddOj7KfmiWv
            xfyuC/Oo+Xi7ccbDg8fusDgjPC6AzIdtW/hv7DjJc4X1ni+o//gKqQfVo8qHtIgP
            =QZN1
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
