apiVersion: v1
kind: Secret
metadata:
    name: installconfig
    namespace: replace-me
    labels:
        cluster.open-cluster-management.io/backup: ""
data:
    install-config.yaml: ENC[AES256_GCM,data:8l006QiyQTC8KtIayHNvjiuSP2mljEZkarFl5jvco/+DvWd7kvVNN1dvt/sfyeyI3DgUD4nHGHa9jheWKFmGP8+bra4J62uG8fB6HemSjLiA4KtjPWfNdo+zjEPzFgO3dc8yxVZXOVI9hSYoqAb3XvpL2AOWE4O9vGH5qM7Foo0zg1lt2wUnvVT5msOfmMPkJzt+oQwLNKlN/f232pYkwM6e873da9DpFPB8dfxsTlpuvlNg7zjjwD3smtnDpo6X+XLXak2SMwrIdSMPJh2DA3fPUMkr13zpgar8VUZ3f5rWlBpDqy8apk3s2cLLteXxKHWy+fTtgcO3AwukspYYn2j4u782Z767sGpONGlV7Sh86ku0sLb25CqTyPVfSAS4CWq/zVa2FflAPy1crJqGSRw7pS/1ajbwpEKj0YCT0fAJ+6P2COoriFFULollwU5E6wwj+65fUDkiY2WSQnSAmmOQm9OHPSLNMXnPKW1Q1QnzONlZUTSxbOQOYrHyFb/mcFtjcE72TlJyuLg2qOJAmPx0qQx+0KfRiy5DZ0OVNG/0rwA+7xTep0j26IYm4wswkIaS6n9ZCeXkPWNQxeaQGsCfsSZ0M+GToMicX0C/mMyU+6OJNobJinEdTJr736ePTuz4xYayON3nbMLwiAWggEMW49suQusYunVQLXcQgrEk5cJTMS9JHFbA/1EUHHduN0qFV5BwTAH35Zn7IDBOj2UADhsPQjGLSXHxkRyOEC0bNW3bJ1sLdmwtolI+hr+zowuY2wpym9HI9mzyzVOeVBkB2Oi8PrDK+6HmUx6x/GQ0w8d5cI0FQxmaTWd81fAk01zjNEF/ykimMGezNTbwAJLlkqYjdmbHP4+t1PTW7RiN3468nfw9IlhuATKnKf9RZr/qpILXSV2RABCQeTvg5lsNuRm7AAeGHQrzt0ouJRgYW3WnBFoO4+FB18xDIGehKXjlH/AOCiMOmLT9Gdwv4Qs1UTiFNq669aqmWFkAwX5tI1gvbaJBeFzHXLmgIHgmr2pTrjnnlMto2OQyeATPzClStNFe6U4KsdDR/32XWD4BKJiOHJhCJT7lJrIWjsfObQtI56pcmZsJTJ40v5Y4Vzz+1FCrcrrGrvObV73Znd5xw5iXZRdix9sJ5TwJNwQx7SIyIx1AngDZssQN6wX6KTXepkYtj106JRehT8ly+1UyRIWOdvpitiWat/Ba1G6mLFXfRyZ9E5uaR1KXPbLTrgG47EowsCrswPswPc7B6aDd5Nj0QOSddQ8zahoWGor4Or1D6fb/DqKtLxt5blliJRHmcVK/JZqEJWozTNA86Yqsuyur+5ojEh6mehuDLdRHmd84pXNDASm4uHZBXGUM2KKbs/LqEz/CP0a6QR2FXTLACkZ2J6Mt1qc2xap0/CV2I9wsHzWbN5LufMIcPLx0akvhvrevPDUQgzxeHnm0TLC8dZFcZogm/8LH+Uc9F96Q2ZkeVUpu+sI79Tj49gdpvucWnFwr4SY2KpcKK4Jy5rgKBLzGrDy6ZQy8MytQN4rFUarlIjZujtSTJPyxNsUNYBmsvamwF2yjTYNA4+bRzvNMyDX202w/FQDQu35upeH7E9WyPV8B/0VU7ga18s3wHMnufKyuX/KE0dN9lc+NwcHbA2WmlH/P9bovrabhmch5sRk3RMnqCBAglR+4U6zMd2J+VUlxvz/MVaiJp4/i3k7CG7EcDmzz3OBalhBpSiCaTMWamFjGyAgKfpk3uaR4NViQ8ARWtdUdYDvUk9TV7M+Dsg15848JkX6oDbv4hoaiPjz3a0GHjKcqSuiPUFTkMUdvSUMLuhLyqMx7zjAClphZn7xvHbOLg7ruP1uqmGqV4rEUtyBjt0/c+ZIxbY/Vf+eKWo+R9nEZwF7/VQHdSonPArGPfPzea6L7tanTvt/cRKxX48PeEi3Jr7Yv7b3sO6lmNzWbHnSJmIfD29KwjANXy3H0/sIK+v5mRCF3AfLr/9tGwZv/tH0EcrcVRAtuEQ==,iv:9x+0wZqIi5pdMFJgy/aPuGlb57voRkOOuXHLeNfdZ1U=,tag:TP234W+5qJ0CHl0cp4yerQ==,type:str]
sops:
    lastmodified: "2026-03-18T16:32:57Z"
    mac: ENC[AES256_GCM,data:MlMBqOmOgWvGLz+awsFokHRef3QcVtkiYQtDpTIbSgcV+ehLd0AdTQjbSRlS1Jv53IDG37sLIz/6T1BYL85N7LsslyunjOkfuxNkBH9DN0XPwrlEfH4CJLrKtNrXeAgxmX2btLO6xkSZQWFn47c8Tq303BTTMZ+f7tAhCPwBX0I=,iv:5m/QY7hyFOntVZlv0+FYbj9CVNyNYGx1EXetz2qnylY=,tag:8DJOIlSF0ctydIEfUCDoag==,type:str]
    pgp:
        - created_at: "2026-03-18T16:32:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdApFt/ftfz20Ufkw9pXhBvf0KdNsrDSiByJinpEohBuR0w
            0pB0dRLUSiRkY99SPPmQPhUqyF+2w7DjFL8jSThJEsfDBF4p+xXL/h94xOASmEuX
            0l4BR8AI4+r0sZdu9WWKn/UjCiBfhNpIo2pmHI6lWzZCFhYMkZKJn/qX6OpuUQVo
            ObfCiWG7pXtdygZVBIhHVrb5hdnfEl8fI5L1AiU/YhPtBe96U/jJfJtPwvjeAsc1
            =YHaw
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
