apiVersion: v1
kind: Secret
metadata:
    name: installconfig
    namespace: replace-me
    labels:
        cluster.open-cluster-management.io/backup: ""
data:
    install-config.yaml: ENC[AES256_GCM,data:9Qw+amwuSothtislXiKPKLF3O+kn/CBkP/MASCFnzAwdx+6szbYoh0GC/O3I235VJmQFveKNACS9/WwPpkUOWTEemfwcd6idPvxo6SQCQu12Tj5SFXdpkMu3by1s1Ii3refux48iKQ4S5+SAsuuiaYW4RYAOQAWaSQw9ZxbarF9XJxiGb/IGFeYszXqP0huQGz9QhN5VqHIULzNKXh74aZX1aBLvrG1FsRbJjb+FfSdpbiAjWdR2NUy9mYkl6G9zd3ZKUdfuWVoLsWY86GqJsVyrxZ4wTtdeRmqSBQKBhk8V3A1ZfO2ORTK50yrRv6HUpXXQljOWiQGrVPipTkoMQ5Ujy1lQxEk76u1Mx7JDStVv9TxC+gfVNjs2my4m4DShPEifhRQwdN9Jrw2CPpXL+XcS2v4Dn1YlfIGz379xeVyxHidICnLGlriVi2ohocIqcDSG2/GMPc2FyWs1rTnKj7rtU/H+t88/WVMx81Jv2BKSfhSBomImgcIb9azWgYE455+TkvW739MmCz5MD3Y7d9rnFkldE1yitQbTaMRdjiFJN5oYz3T6fuqPxTGuZEoX6ToWIBuyLJA/c8eba18twfkEwqAIl4Fv0GgyYnH+m1t6w6gQClBStEZDxNCoUn05Ot0DKYiXOccUsd6DX2cu7R6vs6V7Ywqf3U3jCSiN8oZWOLKZObXHRimJDUk9xV1bzTCUvQcUUXgv6xoZ2ooGIjm2jKMhiQzQyZGfAo/3RPRPKi8U8ZDDqETBBMz0BNtuhadowwAJAECbKF5H52Hjac1+wFEnrE/LCqu3D1jaDvMBDKZnbIcRP1R9jdhxQaG1YKeJ1frsDx46+vJmNN7bvL8b56mb777PGou7sZ46T014IfDATzYi2Qn/iTnCKowLYtVSgrvYbEr86znZk67gHcT8eBihrEsZiutNp1yJRtsjNkOYv8s6UQp3c6Nph6zleBILiJrlXp5b4+oA0bGghLTDmOgqIwgUcvUlJkKGYTZld+QaVw5Gu5ayaq2hLMfPNmmob5e2c2a39ykgFwiXqrNdqc/xK4l/OxHbbjaDtOIK8G54grE/uGshEzYQI5959XhbRvfkIqJI8tg++jHxJrUl+Y5aXNYPGwpx7hXQ6SwpZu7O2LmrmfBFsVVEy3ZtpU5hRIH3gkWAX3wHPlUgBnwc5Djzq715mkNhJXgAgB1yZyemvJkkJmCZgCwWDVCskx4dBMPgUU2Fum3DGZ7N2nbhm7Y2rp9MLuH3P6IzfFcT8UbAc0YX2hB5GU793e7Z8D/+uMi9/4Z8DqzJnbztOqz97J55PZA4q7+LySSyytmGaBpV+QTEucBgIGQTeTu/fnHbq103D53qspaX/dv2UJWqDAQXy2yCA1fjeAjZnOzpv2xbOevU23AfeANkJevtmYSp2rNZJ3EDuusMIj9gOT4GFLTj+dBKnD8Q+nGUM2XHV/LX+ToerNe5h99t2769LH3xf+xgpDD4ARZjpbPiDyHntxfXv4d3kzNPZ8IOgymy+wvwx1R+WdyaNF6iAY+nHQE657KLg3I6RQAtA7Soqb8K8o7R9M25z6alEzUzFqU7jRPj/81JiAdX0j/HmVx+rH6/wciFLip0M2RPhR1mzeobMoL+2nqPDxjC5sUpBHpSxAUJ/qkBc8ohFSSKvzNk93ZiKHSoZtX3xmiCJ6LQdS407kJHB07E4kHX1xF5ZlFDBaTYsnMqbcOgjMS36n8/oNE2gIg0bpjm0t9MG2rdHWInmSAUR8F/Q/iJkGzFQnD8naDQIr0HjnIpx2QtYV8YbM8m6m87DmFEVb3VuXm+KYelzagGzWXpOqOsdy0rvVX+lDdALTK6qTlCiPjWE6u3UqlNqeYkrwCQVdWQTAr0Zm279sB8m17oafVO+3uXOxreBQvR0/hBTR+G4I/zYYD8VVm+O7HWhl6zvKvAq9U/qGpRvsC/SAT4zBFEF39qCWkqlwGj4MYjZPL9Wc7UYu0iMKG/zKDKhL70DaWd32KxoA==,iv:369+Gxw+JT6BYV9w0pxvCmeKzTnyTW71y5TmXZeRxxY=,tag:Uoi0xv8bI01OF3DG0NE8XQ==,type:str]
sops:
    lastmodified: "2026-04-09T17:37:39Z"
    mac: ENC[AES256_GCM,data:hjaR6vQnn9AKpG50vn5cU2a4Cx0DN32CS6/CCQqyomsIdaCswXE18SAdE/jCzTDtHDwuFEa6OdAVPlaSEMsvM0qrEM5pL3QLlW1N/l+G+4uhgV8qNDq56bmj/nwN3mROq27VbvvydH9UfIo09X+tX+D+y1jGSRLbDXzWIR4GQT4=,iv:rwe4rTwqR5nTRi9ARgDsdR7n7x6heUC+U1EOi9X+YDw=,tag:LxUgq9pOJ9kIE103ri06MA==,type:str]
    pgp:
        - created_at: "2026-04-09T17:37:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAFDMoeTmL+/rZ6z88KY8XvdKMf9t+U+bv6kmgOlKPkxsw
            EDNzadIoP85q115iN5QMdt+LfTx2XgNUmv8vGjwZ2pH+Uf9sLHUA5tFt2bC0pACk
            0l4BE3CB55kUrOy0wc1U3AeJvq0aWVYTPggZXBensTvpXmZ4ZhuYh8lCuzSQH+qk
            tXXHHlCy8aZ/wR8By5f2uYY6bRfe7wiIuFsQz2swK3eTB6JsR2lFQ6rKou1WBIBG
            =Z3/p
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
