apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: replace-me-worker
  namespace: replace-me
spec:
  clusterDeploymentRef:
    name: replace-me
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: m5.xlarge
  replicas: 3
