apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: managed-cluster-aws-infra
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/resources/argocd/appset
  wait: true
  prune: true
  force: true
  patches:
    - target:
        kind: ApplicationSet
        name: replace-me
      patch: |-
        apiVersion: argoproj.io/v1alpha1
        kind: ApplicationSet
        metadata:
          name: managed-cluster-aws-apps
          namespace: openshift-gitops
        spec:
          generators:
          - clusterDecisionResource:
              configMapRef: acm-placement
              requeueAfterSeconds: 30
          template:
            metadata:
              annotations:
                apps.open-cluster-management.io/ocm-managed-cluster: managed-cluster-aws-apps
                apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
                argocd.argoproj.io/skip-reconcile: "true" 
              name: managed-cluster-aws-apps
            spec:
              sources:
                - repoURL: https://github.com/carlosonunez-redhat/openshift-for-multicloud-demo
                  targetRevision: main
                  path: ./infra/cluster/aws
              sources: {}
              destination:
                namespace: argo-resources
                server: https://kubernetes.default.svc
              project: default
              syncPolicy:
                automated: {}
                syncOptions:
                - CreateNamespace=true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: managed-cluster-aws-apps
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./apps/components/resources/argocd/appset
  wait: true
  prune: true
  force: true
  patches:
    - target:
        kind: ApplicationSet
        name: replace-me
      patch: |-
        apiVersion: argoproj.io/v1alpha1
        kind: ApplicationSet
        metadata:
          name: managed-cluster-aws-apps
          namespace: openshift-gitops
        spec:
          generators:
          - clusterDecisionResource:
              configMapRef: acm-placement
              requeueAfterSeconds: 30
          template:
            metadata:
              annotations:
                apps.open-cluster-management.io/ocm-managed-cluster: managed-cluster-aws-apps
                apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
                argocd.argoproj.io/skip-reconcile: "true" 
              name: managed-cluster-aws-apps
            spec:
              sources:
                - repoURL: https://github.com/carlosonunez-redhat/openshift-for-multicloud-demo
                  targetRevision: main
                  path: ./apps
                  directory:
                    recurse: true
              destination:
                namespace: argo-resources
                server: https://kubernetes.default.svc
              project: default
              syncPolicy:
                automated: {}
                syncOptions:
                - CreateNamespace=true
