---
creation_rules:
  - path_regex: 'config.yaml$'
    pgp: E31F3444A6E97FF1CE32085C7C1D2B09863AA317
    encrypted_comment_regex: '^[ ]{0,}encrypted$'
  - path_regex: 'cluster/.*.yaml$'
    pgp: E31F3444A6E97FF1CE32085C7C1D2B09863AA317
    encrypted_regex: '^(data|stringData)$'
