---
- name: Deploy demo environments
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - include_tasks: tasks/preflight_checks.yaml
      loop: "{{ environments }}"
      loop_control:
        loop_var: env
    - include_tasks: tasks/create_backup_s3_bucket.yaml
      vars:
        settings: "{{ common.dataprotection.settings }}"
    - include_tasks: tasks/install_fluxcd.yaml
      loop: "{{ environments }}"
      loop_control:
        loop_var: env

    - include_tasks: tasks/create_flux_subscription.yaml
      loop: "{{ environments }}"
      loop_control:
        loop_var: env

    - name: Import GCP cluster into the AWS ACM hub
      include_tasks: tasks/import_managed_cluster_into_acm.yaml
      vars:
        environments: "{{ environments }}"
        env: aws
        env_to_import: gcp

    - name: Import AWS cluster into GCP ACM hub
      include_tasks: tasks/import_managed_cluster_into_acm.yaml
      vars:
        environments: "{{ environments }}"
        env: gcp
        env_to_import: aws
