apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: replace-me-imported
  namespace: replace-me
spec:
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  policyController: 
    enabled: true
  searchCollector:
    enabled: true
