apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openshift-acm
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/resources/acm
  wait: true
  prune: true
  patches:
    - target:
        kind: HiveConfig
        name: hive
      patch: |-
        apiVersion: hive.openshift.io/v1
        kind: HiveConfig
        metadata:
          name: hive
        spec:
          globalPullSecretRef:
            name: ocp-pull-secret
