apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-resources
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/resources
  wait: true
  prune: true
  patches:
    - target:
        kind: MultiClusterHub
        name: multiclusterhub
        namespace: openshift-cluster-management
      patch: |-
        - op: replace
          path: /spec/overrides/components
          value:
            - configOverrides: {}
              enabled: true
              name: cluster-backup
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mch-backup-schedule
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/resources/acm/backup_schedule
  wait: true
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitops-cluster-apps
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/resources/argocd/cluster
  wait: true
  prune: true
  patches:
    - target:
        kind: GitOpsCluster
        name: replace-me
        namespace: replace-me
      patch: |-
        - op: replace
          path: /metadata/name
          value: gitops-cluster
        - op: replace
          path: /metadata/namespace
          value: gitops-clusters
    - target:
        kind: Namespace
        name: replace-me
      patch: |-
        - op: replace
          path: /metadata/name
          value: gitops-clusters
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: managed-cluster-gitops-mcsb
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/resources/acm/managedclustersetbinding
  wait: true
  prune: true
  force: true
  patches:
    - target:
        kind: ManagedClusterSetBinding
        name: replace-me
      patch: |-
        - op: replace
          path: /metadata/name
          value: global
        - op: replace
          path: /spec/clusterSet
          value: global
