apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-acm-hub
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/resources/acm/multiclusterhub
  wait: true
  prune: true
  patches:
    - target:
        kind: MultiClusterHub
        name: multiclusterhub
        namespace: openshift-cluster-management
      patch: |-
        - op: replace
          path: /spec/overrides/components
          value:
            - configOverrides: {}
              enabled: true
              name: cluster-backup
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-acm-mce
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/resources/acm/multiclusterengine
  wait: true
  prune: true
  patches:
    - target:
        kind: MultiClusterEngine
        name: multiclusterengine
      patch: |-
        - op: replace
          path: /spec/overrides/components
          value:
            - configOverrides: {}
              enabled: true
              name: managedserviceaccount
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-acm-clusterset
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/resources/acm/managedclusterset
  wait: true
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mch-backup-schedule
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/resources/acm/backup_schedule
  wait: true
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitops-mcsb
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/resources/acm/managedclustersetbinding
  wait: true
  prune: true
  force: true
  patches:
    - target:
        kind: ManagedClusterSetBinding
        name: replace-me
      patch: |-
        - op: replace
          path: /metadata/name
          value: global
        - op: replace
          path: /spec/clusterSet
          value: global
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argocd-server-options
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/resources/argocd/serveroptions
  wait: true
  prune: true
  force: true
  patches:
    - target:
        kind: ArgoCD
        name: openshift-gitops
        namespace: openshift-gitops
      patch: |-
        - op: add
          path: /spec
          value:
            kustomizeBuildOptions: --enable-alpha-plugins
            repo:
              volumes:
                - name: workdir
                  emptyDir: {}
                - name: sops-gpg
                  secret:
                    secretName: cluster-key
                    defaultMode: 0400
                - name: sops-config
                  configMap:
                    name: sops-config
              volumeMounts:
                - mountPath: /.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops
                  name: workdir
                  subPath: ksops
                - mountPath: /.config/sops
                  name: sops-config
                - mountPath: /usr/local/bin/kustomize
                  name: workdir
                  subPath: kustomize
                - mountPath: /usr/local/bin/sops
                  name: workdir
                  subPath: sops
                - mountPath: /sops-gpg
                  name: workdir
                  subPath: sops-gpg
              env:
                - name: GNUPGHOME
                  value: /sops-gpg/.gnupg
                - name: XDG_CONFIG_HOME
                  value: /.config
                - name: SOPS_CONFIG
                  value: /.config/sops/.sops.yaml
              initContainers:
              - name: fetch-ksops
                image: curlimages/curl:8.7.1
                command: [ "/bin/sh", "-c" ]
                volumeMounts:
                  - mountPath: /workdir
                    name: workdir
                args:
                  - |
                    for kvp in \
                      'ksops;https://github.com/viaduct-ai/kustomize-sops/releases/download/v4.4.0/ksops_4.4.0_Linux_x86_64.tar.gz' \
                      'kustomize;https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.8.0/kustomize_v5.8.0_linux_amd64.tar.gz'
                    do
                      name="$(echo "$kvp" | cut -f1 -d ';')"
                      url="$(echo "$kvp" | cut -f2 -d ';')"
                      curl -Lo "/tmp/${name}.tar.gz" "$url" &&
                        tar -xvf "/tmp/${name}.tar.gz" -C /workdir
                    done
              - name: init-keys
                image: vladgh/gpg@sha256:703f8bb71adbab5ff131e1201c0fa302da53a232c35c55b9e599fc9552ef6b74
                command: ["/bin/sh", "-c"]
                volumeMounts:
                  - mountPath: /workdir
                    name: workdir
                  - mountPath: /keys
                    name: sops-gpg
                args:
                  - |
                    # Import GPG key
                    >&2 echo "Importing GPG key..."
                    mkdir -p /workdir/sops-gpg/.gnupg
                    chmod 700 /workdir/sops-gpg/.gnupg
                    gpg --homedir /workdir/sops-gpg/.gnupg --import /keys/sops.asc

                    # Set ultimate trust for the imported key
                    KEY_FP=$(gpg --homedir /workdir/sops-gpg/.gnupg --list-keys --with-colons | awk -F: '/^fpr:/ {print $10; exit}')
                    echo "${KEY_FP}:6:" | gpg --homedir /workdir/sops-gpg/.gnupg --import-ownertrust
