apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-acm-hub
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/resources/acm/multiclusterhub
  wait: true
  prune: true
  patches:
    - target:
        kind: MultiClusterHub
        name: multiclusterhub
        namespace: openshift-cluster-management
      patch: |-
        - op: replace
          path: /spec/overrides/components
          value:
            - configOverrides: {}
              enabled: true
              name: cluster-backup
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-acm-clusterset
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/resources/acm/managedclusterset
  wait: true
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mch-backup-schedule
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/resources/acm/backup_schedule
  wait: true
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitops-mcsb
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/resources/acm/managedclustersetbinding
  wait: true
  prune: true
  force: true
  patches:
    - target:
        kind: ManagedClusterSetBinding
        name: replace-me
      patch: |-
        - op: replace
          path: /metadata/name
          value: global
        - op: replace
          path: /spec/clusterSet
          value: global
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argocd-server-options
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/resources/argocd/serveroptions
  wait: true
  prune: true
  force: true
  patches:
    - target:
        kind: ConfigMap
        name: argocd-cm
      patch: |-
        - op: replace
          path: /data/kustomize.buildOptions
          value: --enable-alpha-options
    - target:
        kind: ArgoCD
        name: openshift-gitops
      patch: |-
        - op: add
          path: /spec
          value:
            repo:
              volumes:
                - name: workdir
                  emptyDir: {}
                - name: sops-gpg
                  secret:
                    secretName: cluster-key
                    defaultMode: 0400
                - name: sops-config
                  configMap:
                    name: sops-config
              volumeMounts:
                - mountPath: /.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops
                  name: workdir
                  subPath: ksops
                - mountPath: /.config
                  name: sops-config
                  subPath: .sops.yaml
                - mountPath: /usr/local/bin/kustomize
                  name: workdir
                  subPath: kustomize
                - mountPath: /usr/local/bin/sops
                  name: workdir
                  subPath: sops
                - mountPath: /sops-gpg
                  name: workdir
                  subPath: sops-gpg
              env:
                - name: GNUPGHOME
                  value: /sops-gpg/.gnupg
                - name: XDG_CONFIG_HOME
                  value: /.config
                - name: SOPS_CONFIG
                  value: /.sops.yaml
              initContainers:
              - name: install-ksops
                image: viaductoss/ksops:v3.0.2
                command: ["/bin/sh", "-c"]
                volumeMounts:
                  - mountPath: /workdir
                    name: workdir
                  - mountPath: /keys
                    name: sops-gpg
                args:
                  - |
                    >&2 echo "Installing kSops..."
                    cp ksops /workdir
                    >&2 echo "Installing Kustomize..."
                    cp $GOPATH/bin/kustomize /workdir

                    # Import GPG key
                    >&2 echo "Importing GPG key..."
                    mkdir -p /workdir/sops-gpg/.gnupg
                    chmod 700 /workdir/sops-gpg/.gnupg
                    gpg --homedir /workdir/sops-gpg/.gnupg --import /keys/sops.asc

                    # Set ultimate trust for the imported key
                    KEY_FP=$(gpg --homedir /workdir/sops-gpg/.gnupg --list-keys --with-colons | awk -F: '/^fpr:/ {print $10; exit}')
                    echo "${KEY_FP}:6:" | gpg --homedir /workdir/sops-gpg/.gnupg --import-ownertrust
