apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
spec:
  interval: 1m0s
  sourceRef:
    name: repo
    namespace: flux-system
  path: ./infra/secrets
  wait: true
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: cluster-key
