apiVersion: v1
kind: Secret
metadata:
    name: cloud-credentials
    namespace: open-cluster-management-backup
    labels:
        cluster.open-cluster-management.io/type: aws
        cluster.open-cluster-management.io/credentials: ""
        cluster.open-cluster-management.io/backup: ""
data:
    cloud: ENC[AES256_GCM,data:FrxsYPAAuZfCgThUkmOSHFXm7SxuX9q/E/aEQbYaZNJQan9Px8WY4jfSwcOm9/nBa0OObvRMYM790B1BuBU01SifukamIEqdFCZlj0P+hnUg33A3rkv70oHc9qalmimYy/x7LdIfpBj4B850f2XVZMi7ZWPafRPBKTvhdEEQ0WSl16eRiieBc2KbkwOGnO0stfpL/a2FeaU/O2cq,iv:tiXKxmcsSdqX6AagJKCUolZ/RkueY4Reu4FuauNsQ4c=,tag:NZXHRo2SM3r3nwHSIStx7A==,type:str]
sops:
    lastmodified: "2026-03-18T16:32:54Z"
    mac: ENC[AES256_GCM,data:lUAs9UzJHo/saUgnXWTvyda9LlE+D1lYHv5rSBsHxzv+E66cW9EReYMKK5vCH8K5U/W0G1J0sXEC3lGM1C5aT67gQuM68LwKatwrV6NtJ4LOmV+L0cwxEbUSE1MdfMukyDe2tMeBhtvaybRlO9eHpwKWKYe+7LVNON6HRVaWJtg=,iv:kOALfrooozZu/3auHtZHyBITm8f0Laso5sA0WaBINbQ=,tag:ryDlU/T7+QDua0aozFuiKA==,type:str]
    pgp:
        - created_at: "2026-03-18T16:32:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAY/USPI1rB3b5Lu2PHD6tdGzhtq4fEASSxE5G3R4Qt1Ew
            rQvCKCYGfbkWwp4bP3HjisBa2AQK5oeP5v7xecsUqoCCV2jNIGyWzIO5lEukw7oZ
            0l4BN+9jk9RbgCATKNwymCFaPG43rspvqibqWPvUpqUTq6ktJi7Ob8HdiIQPYpds
            ldw1Xd2vp9z+2o76iMU5+TB2zaWzGG6St0wr+qa08ydjJYl9a01hZRXoeWkJP5h5
            =ykMc
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
