apiVersion: v1
kind: Secret
metadata:
    name: cloud-credentials
    namespace: open-cluster-management-backup
    labels:
        cluster.open-cluster-management.io/type: aws
        cluster.open-cluster-management.io/credentials: ""
        cluster.open-cluster-management.io/backup: ""
data:
    cloud: ENC[AES256_GCM,data:GWxvqQQ/PjiyTSs7MBcIfo8tzW+1BSkBavwWk+kjIGkdjO0fTUtmQsymMjIBvhpyNKnyGS9pCDkd99XOwZI2r98V5OHV2bYtqe6z41E+NauqeSxcs+nvwfXSXhbwhtWZPxSt9AAGHlRPD2cnw9HX6zfOtfpWbGqC12tfeuavw3G4+In60wbwXRuPVCpwBYa1AI1YAz4tygV7jm/c,iv:lnHAxZ51nOEmTtCRCYEAneyV6cLXM55YFLXhaPmCsnI=,tag:uJc8eRaoDsLw7DB7JRPUMA==,type:str]
sops:
    lastmodified: "2026-04-09T18:29:06Z"
    mac: ENC[AES256_GCM,data:ynYmYwia5Syu8iZwW9TIx7Fl5ELK7ciHMbo/ae4SsJa/A43YgIT6Ve0+nctcJ8hAQ5GOrARWFvWO8edsL4kE5DXuIJ3hJxBvSUPoECmSBDGhldiup1kvmbS1xGygyuma4H8GMsscxkYBdb27uzqrnTKRE1dNrGpX6T7Ehc4Vwj0=,iv:25k5nB/yRy0/VTLf4/DzwyFu86BdxFfauJoGVCN32a0=,tag:82Ly3A/Rsvk4xfgA8RiyDg==,type:str]
    pgp:
        - created_at: "2026-04-09T18:29:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAGtKfisFLOcrvbHNLY60PwPZJuptIxWrCE7sLFM0D7How
            63e2MPHCYitsBxBiXgug+pPyJIJuobrwYejgDtHZa4yIqKiCgE0/6bdR6oq4g7x2
            0l4BrYRfRThLrG3SVUVrK8p1UGqvrBqXJ8OMr40NXgXqnTGkWMZuJB9GUt2zyJRg
            tbwnxFz3LYOVEcrCbTlyYzmVwhwC+2p2rpgE7imUUTs7pwY2x3Ox7+pLl6PyRf96
            =SHkl
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
