apiVersion: v1
kind: Secret
metadata:
    name: cloud-credentials
    namespace: open-cluster-management-backup
    labels:
        cluster.open-cluster-management.io/type: aws
        cluster.open-cluster-management.io/credentials: ""
        cluster.open-cluster-management.io/backup: ""
data:
    cloud: ENC[AES256_GCM,data:VsM06z1AMZx3S5LTeiEw4w1dcaA1yJnObNCtWarRat9iMxKKbtuwYHkftCr7KYpehVQdeeJG6FM5Y1f4/vGkdjH2k22OMO5XwBdfWfXmVR7/2CIOX2aKnR5rjB210zOgbfaY8+buzXojQFBxbMQObkXubacRvyl5n+plEdUt3D4gJ5ly4r2yuV2YppdE4nns6DqLoeDIa25BMv4d,iv:qeU1HrGkLedenpZr8vMeIxHNjZGIKy0HMl6DSSisupI=,tag:+47Gt7DAcXQJ6y+S6XhF7g==,type:str]
sops:
    lastmodified: "2026-01-13T19:26:21Z"
    mac: ENC[AES256_GCM,data:W4c5qu8CnGSv6QNdd0XwnEdWvB9SkDPdBqjhKGHiCOqzAdwsbt5bajCL8EEsaiCSiJce9cmHyFlz0UKtPH/+lUwhh1CJvyL39giP0088sUKzcaUN4ewa3FVdGjlhzkky5xKeRZU9jNaSHKTklq6vIHKxhRuErJtMoZa1P3LLTog=,iv:eHYaEyu0mMa7TWJbfqJuM++3z2pSFEaQ9YNAtdP74Pk=,tag:QF82l5KlxLgZw1iNZXh90w==,type:str]
    pgp:
        - created_at: "2026-01-13T19:26:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdA9xz2B+aEZxknQESJFTCDsXLdngmAJj6XHhoqskbwe2cw
            63bCqQ6rvU8XGFPgAm+zF2Yx27YnUJ7+7yVtcX1LQOKP3M8GRq1Pjry8/OimC0QA
            0lwB0FT5btjyV+S+PnWX2KZgKGYSAiWfQvDl6VBpxExynjftBwzKOmoSp26HUSWl
            W0kxbf1FC1V/3+hC0PeRbI/45efVxxSHVW812XzPgvB9JtCGW5MHEOG2IjvsCw==
            =l1pl
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
