apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: imported-clusters-aws
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/managedclusters/imported
  wait: true
  prune: true
  force: true
  patches:
    - target:
        kind: ManagedCluster
        name: replace-me
      patch: |-
        - op: replace
          path: /metadata/name
          value: imported-cluster-aws
