apiVersion: v1
kind: Secret
metadata:
    name: db-credentials
    namespace: change-me
    cluster.open-cluster-management.io/backup: ""
data:
    username: ENC[AES256_GCM,data:ZHGVFq2IC5PI/KrEnDcqVo3JsbsKIfFoguAwmm+fuPw=,iv:Gi78XNjZ3u2QsS65V9GRFDtOs7E98DLSjHI7wflZ330=,tag:AtP+mAfLTYq9WqfkkqiNMQ==,type:str]
    password: ENC[AES256_GCM,data:DFVa3ZhxpQd+ILJCF8W1K596JjB1pLrEglFy+VhADtqF4MmZNEZnAdZcRbQMOgTgl30rs16DgAyhEfctRujWRA==,iv:VeyoqY1ZD1rpt/PCo816Xr4nDeebtVHW+Pgla/xN08k=,tag:gXfLwaLaBXVluBqkG5hSmw==,type:str]
    database: ENC[AES256_GCM,data:3Ykjt4laM2bOIKH8rn5LasD6f+YFs2c9PKT4hNTmIyU=,iv:AY7lAakCo6KVDA8Z4+HDcFTw+EIN64Btjy+mo35afaU=,tag:9HXyW29uMfuRwrrAF93KOQ==,type:str]
sops:
    lastmodified: "2026-03-18T16:32:58Z"
    mac: ENC[AES256_GCM,data:BEoZXxLRoB78DdRolWKP0WLHJYRlfBv2xEBvrUZO/rNV7MWbbnKSD60XeCtc0A5OKGYjwn9zYh6WMhNmikhzdMGyD4QKg8/UZI24pmPQGx0ESI2KCS5Bm7Z3TnRhmin5TEbNo2WtVD17hLde8Bu7He8ngMnXymZAETfLYpalbrI=,iv:QVpXV4quOJlpBqJQ8Uc8jt/h16kzge1lj22RKnCZgbg=,tag:kjAXL5HM4QkaNNiWugWxxw==,type:str]
    pgp:
        - created_at: "2026-03-18T16:32:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAp/L7tOzSVXGq4iC4QdKY4CpzF39I2n4LLdfOTDSI5DUw
            1CivLev4XD7XntOutn/k1HiRM0HKjLjJqftSR/CxvFgx1SB1H16EiIfITlY1Hmg9
            0lwBzoMTafzwq9GnXopVPCiPI1q0OCxqpU5DM4Ujd1u82MJE2XfaCzQv173mLgAR
            pbe8a5QQ77L4FlvXnTel+mw0gZ4Zu/guTf0FvpvNq75q3PxDguvKfED6sDmjiw==
            =y9Ja
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
