apiVersion: v1
kind: Secret
metadata:
    name: db-credentials
    namespace: change-me
    cluster.open-cluster-management.io/backup: ""
data:
    username: ENC[AES256_GCM,data:6pmjy+O2a6uu+vrG8gZmqYemh2wu7WfoSw7bTxaQXHg=,iv:YxJtrkc+7mrBJE70/gbcogtwGHlzfZOcTp9MsOsh+pg=,tag:KsypQOqVuRr30poXyWjXxg==,type:str]
    password: ENC[AES256_GCM,data:PgXIUhkMkGJQNf4gWbjzibowmIdzdrp36xUAyrjqg31l3Ez1GMZAMarTSSYOta/jC/tVuPbZDUSjkv/t3pJV4w==,iv:3tVXWzEHRNF5uUTtw4HoA5qYx9PblAho19oSQ7HRYK8=,tag:c1ozdCHaVOjHrymwUbr4dA==,type:str]
    database: ENC[AES256_GCM,data:QmX2JE1aGvffwSf2hpK7MqRCNNP4XlZCBnGjjKtnHSk=,iv:2FxGSt7bPSJUr3RueEAOuPYB3oUf6/4A6FZJkq4jhWk=,tag:O+EGnIcFwov0jJYZYW2dAA==,type:str]
sops:
    lastmodified: "2026-04-09T17:37:40Z"
    mac: ENC[AES256_GCM,data:3lKMlmkSeOUEzvQbv/yLuqCHR5skXlY8txnmRdskBQTcqsOESRhDArFoKTSGNpmvIgyC4DI9rqC3xvfXaMabwccWrhEcTJxHiBBaS+OrgpPIip4AZNu6ZMcYRlf0hYQmK3fNPwKvreuHblYVxervghl65cJ69ax4deVyrA28BaE=,iv:ChrA4v6SR4mlv2DgzZVFbULf1sasjbKPSti299Pp8EI=,tag:mYUXw49b1ZopLYPmwGzlIw==,type:str]
    pgp:
        - created_at: "2026-04-09T17:37:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdA09CW8dkEhDLFXg36wGEPTEE8fwWmqsF7Q2/5dJWn0yUw
            dmHxkvktXg5qURYsF3kw3KpHgEIGl+i/PvdAIwg/XefnAk2MMyZG549DNdtuCRvT
            0l4BAo3MkxUYVSwScORvBS1GM0KMmDQcqy/s1gqp8WlS41jVlxYA/9Uh/v0geDpq
            8TElOqJO3xJc0NpT9RL8EknW4AOQn9Gz2pIxzUxHSzeDiY/DFv8h+ahswB2dqeUq
            =TmMM
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
