apiVersion: v1
kind: Secret
metadata:
    name: db-credentials
    namespace: change-me
    cluster.open-cluster-management.io/backup: ""
data:
    username: ENC[AES256_GCM,data:BmN22URlBh+dgJhSHIVhrPO4Z8pg9tm7n8Aybf3dKYs=,iv:hgOUS1BE6Tn6skAGp2IzjA4knz4yf9tok/xG10qPqhM=,tag:j/T7OO8A+jy3YC2w9gnZ8g==,type:str]
    password: ENC[AES256_GCM,data:5qlPaC2f4bxdFLECfOu4eaZ5zFlz6u/VUTookrV/1L5uUl2pEn/2SyfMxIjlAqrBm/2uz/zl8AHW3OkLiTNLvA==,iv:NOd9bOdxOBJL4GIxCAtpsR+3IuhxjZB9b4SmhkTZaww=,tag:2xb5VZZVMK2DKHF8flugog==,type:str]
    database: ENC[AES256_GCM,data:SnHnvaCcLiLPCO5OENFu8MkrMTN+i6fJvRkiApBMNZg=,iv:1W8nqGAc+0mY0bDdtFfTADyrAdaqRATG/jWhBx4stVw=,tag:/pPy5FtnHxxnw0wUke03Ag==,type:str]
sops:
    lastmodified: "2026-04-09T18:17:13Z"
    mac: ENC[AES256_GCM,data:n8Yk52c2XJgNgQXadI1eDzg+vPUVup3wO79oy14PKcCiCkNbkwmfpv+2etwN5uDofkR0NvN4nREHmc2fgmYih0U+dYKKZ3X3Q27uwBhtFCXdjUl2khZoL/hoFfQF8QLjXwNusEd9LMY2Vp1aWqhzQy73zvByvjpOmzsNoQYcEV0=,iv:v7ywnLu44qYWgk3k0DUJJBZoDuFBQJUms5VM2fsgg0Y=,tag:0OmwF4+VR1z61QunIFkh5A==,type:str]
    pgp:
        - created_at: "2026-04-09T18:17:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAE3JvDlIGM5HcaI5m9JRQTC0GQoRIIPOuCuTXU72kmkMw
            CuZ69TaT/1sphdG8gROsYsRlfkXVAMpfwaA91icZEoGviii6qzR4+MxPLW/qlCZf
            0lwB/Xh78uRKcaCyW5PmW7MVWwvr4hW9W6m7A1wRWW97bc9k01FGGQpBrdC5kmKb
            z+ZqJonvFSlVwe485Uv5oPyCWBRi3TwUPDCZETvNFhLyMTfqNGgPUNCg6P5d5Q==
            =ghS0
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
