apiVersion: v1
kind: Secret
metadata:
    name: portworx-saas-key
    namespace: portworx
data:
    saas_key: ENC[AES256_GCM,data:VdOdwxhffQHQKnkHz8MCR/zxFbwa2Eq6Al+StAjVht1Y9YxCeag3AqHzQ68gtgFpDj+t+iIMYPDR190vjKf07Xj/5A0GH3K4ZPuy9LLlktg8EhWiU1PxMsM8DHmQ1SWATsSKlgbNG8mCbWr1OZqBnu5wwzuUZsIc9mj5L/vUcEdudezWpJriYXiBwPWuwYnDTJ9bmnC8YNDvbS3N+UF/1gpIGF/KbnaWF0hqBeodR6wM8DhAH+BhwApn3Qql8S+J33ypJIB1ZOG37/xwi8aO27xWNIxA1MOgSeJYRpiL6187JCnAJAoUMq6R109wsjNpJ+qSAc0V6hxQn/BWASEBg4NFES7B5CPdxHtxzIA5Kp0bdSruyGkJDlMKRdOiedc93KQQBJzJahjpd7MBu+AHMMCH5ItiA5SzigFin1fmoINA4P8VmnlfK1yl/ptcaNLNUwB1AZrpI5w5x+n/PQ2maXv4fcu57QpR8yx9kIRuesA9HQgdFH+ABcWFe3dxTZdIBUGZCVVaDpwLbIznr0LJYB3luibEY7GnSgXBvQnhY1mSktjgBBgx/z/InREPNI2A5uKdnFxR4pWOzNM6ECCE3XYn2FsaDSsI/Ld1WhSkHLtMON1SPmuLV0cKMletOLHGylYAuUf3R9VTaOCgifXL1F0gyEHTD/AmyDOaWzGBKqNRfbuPZDQxmadcbKMEv9GzEPlpL9jE5DxiPB303P2UZqvrtA/GdfizY6aRtuRl9oP0zFhp6i2QJCyrhqA=,iv:IfyKfPogfrPyzyMZQQEGBZCHza2JA8Jcrf0+Km2Mikw=,tag:bklVz68YwcuaFLpKknNHig==,type:str]
sops:
    lastmodified: "2026-04-09T18:29:09Z"
    mac: ENC[AES256_GCM,data:3GfxsQXHjnOENHjMqWMKImQAmnHyGH+F1D2c+t03FV2L4aAJngBEnD3Mtvzgpu1QoUVxJKcpHViReVcnoiGPt/UxmTW/89sjKfVf07v5c6BuMqceU9ct6JoiDL2zGci8wNtOQJft7rPKNZfEH1LTnaBoQ1ia/B1JtTY2c7pIVIE=,iv:0RNWIwHuV8BUS1JriJ/nALE7XRWendmM1LysliQvcLQ=,tag:MZ9Kto79oIUIsQS49y+b9Q==,type:str]
    pgp:
        - created_at: "2026-04-09T18:29:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAteX9/Y5KOHNFerpqMBquEKGamos3zbAfZ8iegL73p2ww
            c5CL7aSKgBvvxjBZufxPuBy8heXGbhTED1DpQ0TEK24bo+xuy0dO/UyOV64WQZn5
            0l4BBqukah3J7NBgsGyKqEghzbEyHpe8TPRU9zWJIMqzF/TvEUzD6QhBsV+k+hI3
            D4Y94G6N1+urb1Ofd0PxNsLMjgAjQIkUfj22BduW/uPT/Pf7MQ87cjCbaCSk+LmE
            =XDXn
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
