apiVersion: v1
kind: Secret
metadata:
    name: portworx-saas-key
    namespace: portworx
data:
    saas_key: ENC[AES256_GCM,data:f4W8H0vnHMRUZe2VVsULFO2pHLzsAcje2VdGQPreEAo0sHdlO8wrNB5nUxh+lLUq24SJV4bqap5uhFJi6u4cjLGPlS3+Pv/pVUVIhUwQJtyI8kaL36jhAdwrpFiOp+WEzaWYgcCF4zDFCSbdTU/PR/urvYZxxaWbObF2SFB4jmuMtjBdpT+FLDeAo1RKVOUx4mR7u0XEHJYPhn4IjV1yAuGZryatpFSv7d+QVQQuRQx3NBF1ROdkK/I7LU9oNc7RimR/IJRnWSUfaCmWqj68cdI0I9/+brV76xz/tJXAFONJhpe7sOCTTd8vUtMeihPMx7DIs/fui5lIYzAnG0wW27G3Fc88B9bWmh3esn0R8Kk9Vzg27X0dDUEsXajUqt2zI7rUsDtbagwjdInGy8xFe5EYn92I/z5s95Q3xiQ1MUJi6oTAB6mO4kUXUwKUXBDo8Xuc8EuHKFaUJIMA9iT8/A7mZmSiA/Ruwb+wRk1xbBhMhpqrCwTy5bpXQLRj2XRxVX88zZ00YQVimJOZ1CoE9Ld8zzJ22y5t7tHk9WGYeiBHVyuc94saU4K5qhe1D6L7kee5t3ldErlK4ddLczmOUFVd0eC8ceHkNo6esduWQVACOmdoKTNJTCLKvBdI91FfvuqnJdSjr4dqKbJl+I3xHPrMWCC7Sv0ooTPy5CEN0rtAppIXRxh9cYg4RzWxru8z9d2ZrX/tAefW55z6LrzbhGkuCJSRo2alLGzVfcO3vqWRoZn/eWg0dbVpK2A=,iv:Ijv01lGb19KlGPj42pzj6gUspD3D5mFzfS5OFWHHCA0=,tag:g1k/2QwuSERM6HGdkKkz+g==,type:str]
sops:
    lastmodified: "2026-04-09T17:37:40Z"
    mac: ENC[AES256_GCM,data:sA5gtnP5DQmI1jNR0FRMoSmxrQpVKw76RYbRD7zA9DWII0iBHNPiM2GwmhY+4aKpoGrctv3YXQpl2Ih5a/7Cb0UR4Br4TdP0SR8Rquyc3xgxFZ/sk7oumpnUegf1aUQbNlthnPL1wkN3uZPiAtzLish+K06CzFjP7ETBBJVMrUs=,iv:17W+s9JTaE/CA4uPH/Gn6EnNideitUOXQK0OrGp3AsY=,tag:jWKjnNtFNx1wlPxAthU16w==,type:str]
    pgp:
        - created_at: "2026-04-09T17:37:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAMOf38e2rEsU/s/xDZlKBze6BJidU2PCXVPBpM138jiQw
            01kRs3uQ5Q2KoiXwFqlpoEfdYEEMyqAAUHGJPESLQ4x5uasv0iWAKeyTItdKYdTT
            0l4BiU/AjYlSqPdvAmiyQTZ0E7NEsY8EX25tI8zylHuyxi5Ja28T6orFZo7HUxdP
            kFKcF1PaEAM2VrqLlD/ReY2zq609lC6O75MPz3zg0mEEepQu+0K6jFdyd78ZdDCq
            =X4Rn
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
