apiVersion: v1
kind: Secret
metadata:
    name: portworx-saas-key
    namespace: portworx
data:
    saas_key: ENC[AES256_GCM,data:EBMQnPljPKyYa6R6bRoUs0QOJWO9Mv7qA4fsdP/OoJtXFTX+WvuhLItkeuzhZPqb8li+BqhDUlUN85SnXwja6WO4vDY7KZRP9j1VwpOi1/T9tKOCnPyk5krI/5aXDurAI+V/RY0me/HSOBRhEILJq6/HfhSyidhNtHgKij3Q4ArHx3WoRte0tddGa5/GpvVclokSDNzMNxREkl8fLNJgXyzu8ADLBjx/SoYCKhFrt8hl5uXV8RP67IMOjmDAQBuSrA8/SaTwGK1iDRBOYyO8uucEDtkQgbj2bTALo++Q8vPPinhVqvfUnZriZLzS3xRUO4IYSzml0Jdk1z5e1oOKJdI+psLFvamwNloMsTaPCgLMz8+I924DIoEJGLq3z8UO+xIKvK/BAJHiDzS1M5OueDcd6nwKvD5c4xTVWvDYYCw+iKiRof3LjrxO260rZeRFncYBUF5vbF5vdngHygxARQCIhnQ2VEZzHLinXviRmr98hQTtPUd0RajMhmitSYVqOdiju17Gqy39NDxtVKgg9bkc7ho2DeJa/JFjLZOhNHY8/MGdTRQFakTsfvEraMxNDdN/kfvbhTumpdeO3Nw/iVCtKgP+h9xWX0WSpm9hgORn3YQ5GB2/WGjff1AVIEgfen+9UKnqLh0xVjv07pc7Aq1ofyrFQEtbqAAmiwaPKwijxgKM0/ZjXs4LvqpeMx7gQTMnQRXcCDNke/nboR2A87XUfppyi0T76KDJ74QvTBs23KX0sjxr8otXK0M=,iv:+mNa8xrF9rQN1Wn1wyh7pwlkhlj/WJ5hnJryrulSSCA=,tag:H83i3EWCR2WSNU+ImsIf6A==,type:str]
sops:
    lastmodified: "2026-04-09T18:17:13Z"
    mac: ENC[AES256_GCM,data:LYOYpR54fQg49OnBcapKfrlzqERe+kfK+Qv4K+dk1VYKpNtHMmhUGryzHGF1kFpPiam7OaxNpm75V+yNohqxLbYaTJp/9hbdkw1E4RD8U0Hukfflm2oIW/IVwQanS/9kFHU7L85WCfUVqFm8WzML+ZlMQW++DUEeB0B4SQCx11E=,iv:Y2zFldmkM5nERvkfmAfzwItlhnW9SiXjM/8pYMn5B5w=,tag:+DPkxMwOBJpdbGSB2eWCMg==,type:str]
    pgp:
        - created_at: "2026-04-09T18:17:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAPC2mgJNRFDnf2QhRLJU6nx/O67+/FEjQpLUPKsQI3zMw
            p+ZjPJHvWdfTbhKOTqyurWVwz/N1s2LwMxJbJNDr7L6BLmICTSQxqSdJeXSNo/56
            0l4BKUtpyWS2WTlVRMv8ch4/oBqnCc093zOuL6hE5TJwtbj4W2sj/z2VWNt7y2MF
            q7OsIoX96/XJNlaULMP/K6cCbKdSiw8jARzvpY7C5HJaLdXRZkRiMniiDBfdRXWI
            =2K6a
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
