apiVersion: v1
kind: Secret
metadata:
    name: cloud-creds
    namespace: replace-me
    labels:
        cluster.open-cluster-management.io/type: aws
        cluster.open-cluster-management.io/credentials: ""
        cluster.open-cluster-management.io/backup: ""
data:
    aws_access_key_id: ENC[AES256_GCM,data:05pxQgdtOU5UFlVSe6gOn3Hw8K75gi2YtoWlZw==,iv:12TNN2LlWpkbnvdVUVzcdgcPVmzIllaTS3Bx3evipu0=,tag:DACvSryBgjxAp92dxuIkFA==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:NvAlpZQpRc95SSiEfIehqC36G+72lzJ8Env7CTz3lPQwnj2LdUIxOw7+rlGPM9dx3xnHmWnCDl4=,iv:JXwJdycyql0KZ4Tc80fO3yj3aCOg1uCp7FihczUka0g=,tag:wyfmgq/fFeIR8WPk/JL4Cw==,type:str]
sops:
    lastmodified: "2026-04-09T17:37:36Z"
    mac: ENC[AES256_GCM,data:Njp1Tp7c4MXuef7MgmW1aKZ25TIpKOdLy51/7hsmnC7rRSCgnzrtT2KYZDwwRxRDbCkVRthSOX3/G5UeFDf6fBvxWM4oFL8mqHec0uxpKOSTpDVq+Pr4DvnNx51uVFmmSCpHY+Y5gqIpGVMCmDxh/v+BVuSDFQ4dNG8RcK1dJhY=,iv:RWhwCb8Q/T4f2xbrk/9hE3lXyulv34LNnyz6V4TCw/0=,tag:6r97VCvjudbcAUO6K+mbpQ==,type:str]
    pgp:
        - created_at: "2026-04-09T17:37:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdACy64Bfjor2WGshRDtxtRRIShmWv5aeqdUguiD9lRhT4w
            WmT8vythkgd0roPa7dJ+sEFneOjgMxaIwQSCPTVnUY5peavSkeitR3pUKuqYcp2R
            0l4B5ikmzFr/VjjxKNjBA4MiAZ8bTRVnyw+/ZOE+fvvl7XLB41q/yF0IRioA94Hb
            9tYDbnwp/QkEBBuePc8DLqKkyeB2yhCHx1bAZ0jUGbNp2FLVSA6wGCKcJv9vFFh/
            =ccwN
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
