apiVersion: v1
kind: Secret
metadata:
    name: cloud-creds
    namespace: replace-me
    labels:
        cluster.open-cluster-management.io/type: aws
        cluster.open-cluster-management.io/credentials: ""
        cluster.open-cluster-management.io/backup: ""
data:
    aws_access_key_id: ENC[AES256_GCM,data:ZNCo/R9mHrG7o68jDAMwQxWHsuHHOz4a3bC+YA==,iv:dquB9GyXVr5QlkhVLF8QMO0HeYfnEDyxpthqkuF6+vQ=,tag:limIctn4IOeQskhaSPm47A==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:BD28+QtQRBmXtBqSWCe1IYiaEmzx+3WNnQ/LOOBi+S5Rat7xEXC3+GYreBPGZ9MaHezx5xe2uVA=,iv:8NGhsbhV/cfbRsQRbyx36N2zRsouz7Wq4BCtTDPZ0fk=,tag:KHpY0nqxaNfdm5nel6Hk2Q==,type:str]
sops:
    lastmodified: "2026-01-13T19:26:20Z"
    mac: ENC[AES256_GCM,data:4SQvUaveU2PdiJIwjV8L5mY9gt7sZ308qOAMk4o2mT5BjVt4ZTAn/zn4I/6F7uDUuP3D8TyXc2vmlZUKrN3OqOOWra7OhgzJz+xb3jVFZFK5E4K55sCIpd06pKbXsg3joRx/XZMJDdv74V92C0W3bGx5M3ms+zMSzOnUCoU2DRA=,iv:ikgFoBzn2r1kjA5p/o8y1zd94JK+uKyBYHSR98kLcks=,tag:39vAUWaoi7W9trPKnCC8+A==,type:str]
    pgp:
        - created_at: "2026-01-13T19:26:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAaWajzvAGoLet5OvaWFI3wPfvMb/ysGXcbNgAK0JaPAQw
            l0xQ1ZSTMKSIgFCS6wX9LKnDenj9Osv6J4jX8UIbAsnfQL1qif3GEw9ppBbFBPpb
            0l4BpbsOwmlJnVCVvAqw1mBxv+xcnP+ylLoPBxB5yKwDjn2AYSm5eDbkdWGgvjsm
            24CkV0Bt9HzGrshnDBH5KtlvRZd3Rh5C6q399X+CeeAVtLOGlMmqebUUKCOtLrRb
            =WwQE
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
