apiVersion: v1
kind: Secret
metadata:
    name: cloud-creds
    namespace: replace-me
data:
    aws_access_key_id: ENC[AES256_GCM,data:6WEu27Dv2+Eh84/p7eTWTUwvQOR4o5fJbIqKWA==,iv:dHCkyvOefYBzq7rhPBv9HoZaaLA9Vj7m0XMa6HdLt6Q=,tag:GoD2uCorrKlc0hIkj4AquA==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:QVInoYxUqePWNAJwelUrEkmGp3q/phQArs9TxkPZ+udfk7HvG270EaG9RykL7ek7Djgmb1RcAMk=,iv:R0B4UCaWB0eSELcCC58bwio0LMLvyz6Zkds8jNGPGSI=,tag:/5TuRDzPHGZnf+hl2gp2Fw==,type:str]
sops:
    lastmodified: "2025-11-01T18:35:17Z"
    mac: ENC[AES256_GCM,data:ycGrf+L6zLXnwBEVoOhICOAfTEWZoKoHAat6ilTiCbDJB8Ky/qdHJrn5cB5nHddK7bqFveN+ZImJueHNe0EwnIE/FY53SZy8L1NJV+T7sLiUdz5dUaKmhR0J0TqUhIF2yF7cwD6iyFvawmW40dkm1Nqnz8SmrlkP+AYiy0nhADM=,iv:J0lJ8jg+9JUq1fRm7tImDanMp/+R5AdO5YHi6x9EkPM=,tag:JebDMAt9DPBzxvL8U1WXdg==,type:str]
    pgp:
        - created_at: "2025-11-01T18:35:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdA9spluIEvva8gjqVf1tsSaH5MFFK36MCs+YBsS8uqOzEw
            7LUdVfnQgbyezH+iq7TI0Iv44vDJ/4q4eC9hqORyhLW7ONe8ifT8iDJqB7pb1orR
            1GgBCQIQFxM3XgHPZk7fm2IXHB1CtY0oC+LyEVSd5EI2PpCEkDKz4RfV9kWo6Mvj
            FZQxjx1mfZmP15MhZDm5TpeIyq5q1kBQOeDo54vRxrXtp1MlQSUcJvXYWQ9CIBmc
            Kx3Rh4Xe3+DZZw==
            =cqeI
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
