apiVersion: v1
kind: Secret
metadata:
    name: cloud-creds
    namespace: replace-me
    labels:
        cluster.open-cluster-management.io/type: aws
        cluster.open-cluster-management.io/credentials: ""
        cluster.open-cluster-management.io/backup: ""
data:
    aws_access_key_id: ENC[AES256_GCM,data:6CMBVCJsJAXS7Mstdla4EQcuxQB0GClpEGsj/g==,iv:QGbymcAZdcvB+m+IdUmHFk24lMGQgzilV9+AUXqoZu8=,tag:/2XMoxr62pzbxR7fTdJLRg==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:b+QiYKdpMhbG5wmvrLZgcndKydA+rthHTCODcnNkjf3C9arvOI/eTejVSqx/ab9V5PpNNO5lDMo=,iv:h7Qdon9g515/PNQM/6SnsGdoBC9xFEQAUqPqLo0AaWs=,tag:oeN1KlfB/TYlY2bTCZZHHQ==,type:str]
sops:
    lastmodified: "2026-03-18T16:32:54Z"
    mac: ENC[AES256_GCM,data:rgxMTMtTbjf3pHSgW/WFgE4+4fkoAyhRAnp+5J68REtR3MiGJAkgh9GBBszAlKu7vysbYemEsyFrQtPNbR1MdaLM2Lu9uY4vfHskq8++1BdpW8AOyz/TSdVVsSVBCQ01i1TCYSaoWvYd/oqb3EQhQL77iM4k0ceFNlEsHFG9PoA=,iv:inZHt5gLP8YHBKcuHeSUnVlopiNKcMUieh9aSmrbG2w=,tag:Oka9VUBiUkWNSqETALUXoQ==,type:str]
    pgp:
        - created_at: "2026-03-18T16:32:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAXwsrdWLWdcxeJUQ/ZoSfQqPRDHrYv2qocovjMlazwEAw
            VRVm95Nmr2t70FCCaa7tpZOdnFm1nwR0gaBzR8YqxUtA7wmDpnV9fnVSYU6z4Tg7
            0l4BhbtkzNTktgMOo0o3fB8VGrfOQuAxRZ+RUywRV/SkwlwJ+9CxA4WS63WY6SqB
            Bclz3cpIoppn3UNxFVLvHm5XXk9kxnXqxX31vTr+2HckGJlvbO1uV+Zay3+ZHOfB
            =ByIu
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
