apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: managed-cluster-aws
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/managedclusters/aws
  wait: true
  prune: true
  force: true
  decryption:
    provider: sops
    secretRef:
      name: cluster-key
  patches:
    - target:
        kind: Namespace
        name: replace-me
      patch: |-
        - op: replace
          path: /metadata/name
          value: managed-cluster-aws
    - target:
        kind: ManagedCluster
        name: replace-me
      patch: |-
        - op: replace
          path: /metadata/name
          value: managed-cluster-aws
        - op: replace
          path: /metadata/namespace
          value: managed-cluster-aws
    - target:
        kind: MachinePool
        name: replace-me-worker
        namespace: replace-me
      patch: |-
        - op: replace
          path: /metadata/name
          value: managed-cluster-aws-worker
        - op: replace
          path: /metadata/namespace
          value: managed-cluster-aws
        - op: replace
          path: /spec/clusterDeploymentRef/name
          value: managed-cluster-aws
    - target:
        kind: KlusterletAddonConfig
        name: replace-me
        namespace: replace-me
      patch: |-
        - op: replace
          path: /metadata/name
          value: managed-cluster-aws
        - op: replace
          path: /metadata/namespace
          value: managed-cluster-aws
        - op: replace
          path: /spec/clusterName
          value: managed-cluster-aws
    - target:
        kind: ClusterDeployment
        name: replace-me
        namespace: replace-me
      patch: |-
        - op: replace
          path: /spec/baseDomain
          value: sandbox591.opentlc.com
        - op: replace
          path: /metadata/name
          value: managed-cluster-aws
        - op: replace
          path: /metadata/namespace
          value: managed-cluster-aws
        - op: replace
          path: /spec/clusterName
          value: managed-cluster-aws
        - op: replace
          path: /metadata/labels/region
          value: us-east-2
        - op: replace
          path: /spec/platform/aws/region
          value: us-east-2
        - op: replace
          path: /spec/provisioning/imageSetRef/name
          value: img4.18.26-multi-appsub
        - op: replace
          path: /spec/provisioning/sshPrivateKeySecretRef/name
          value: cluster-ssh-key
        - op: replace
          path: /spec/pullSecretRef/name
          value: ocp-pull-secret
