apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: managed-cluster-gcp-gitops-placement
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/resources/acm/placement
  wait: true
  prune: true
  force: true
  patches:
    - target:
        kind: Placement
        name: replace-me
        namespace: openshift-gitops
      patch: |-
        - op: replace
          path: /metadata/name
          value: gcp-gitops-placement
        - op: replace
          path: /spec/clusterSets
          value: ["global"]
        - op: replace
          path: /spec/predicates/0/requiredClusterSelector/labelSelector/matchExpressions
          value:
            - key: cloud
              operator: In
              values:
                - Google
            - key: name
              operator: NotIn
              values:
                - local-cluster
        - op: replace
          path: /spec/tolerations
          value:
            - key: cluster.open-cluster-management.io/unreachable
              operator: Equal
            - key: cluster.open-cluster-management.io/unavailable
              operator: Equal

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: managed-cluster-gcp-infra
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/resources/argocd/appset
  wait: true
  prune: true
  force: true
  patches:
    - target:
        kind: ApplicationSet
        name: replace-me
      patch: |-
        - op: replace
          path: /metadata/name
          value: managed-cluster-gcp-infra
        - op: replace
          path: /spec/template/metadata/annotations/apps.open-cluster-management.io~1ocm-managed-cluster
          value: managed-cluster-gcp
        - op: replace
          path: /spec/template/metadata/name
          value: managed-cluster-gcp-infra
        - op: replace
          path: /spec/template/spec/sources
          value:
            - repoURL: https://github.com/carlosonunez-redhat/openshift-for-multicloud-demo
              targetRevision: main
              path: ./infra/cluster/gcp
              directory:
                recurse: true
        - op: replace
          path: /spec/generators/0/clusterDecisionResource/labelSelector/matchLabels/cluster.open-cluster-management.io~1placement
          value: gcp-gitops-placement

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: managed-cluster-gcp-apps
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: ./infra/components/resources/argocd/appset
  wait: true
  prune: true
  force: true
  patches:
    - target:
        kind: ApplicationSet
        name: replace-me
      patch: |-
        - op: replace
          path: /metadata/name
          value: managed-cluster-gcp-apps
        - op: replace
          path: /spec/template/metadata/annotations/apps.open-cluster-management.io~1ocm-managed-cluster
          value: managed-cluster-gcp
        - op: replace
          path: /spec/template/metadata/name
          value: managed-cluster-gcp-apps
        - op: replace
          path: /spec/template/spec/sources
          value:
            - repoURL: https://github.com/carlosonunez-redhat/openshift-for-multicloud-demo
              targetRevision: main
              path: ./apps
              directory:
                recurse: true
        - op: replace
          path: /spec/generators/0/clusterDecisionResource/labelSelector/matchLabels/cluster.open-cluster-management.io~1placement
          value: gcp-gitops-placement
