apiVersion: v1
kind: Secret
metadata:
    name: cluster-key
    namespace: openshift-gitops
data:
    sops.asc: ENC[AES256_GCM,data:iZmPPWfFcGP5FazVdWsbsdwBlQji2OKr7RyfE989puPaleZDp9hWMClAnVzFXnWNHFV/FL/j0JcNGoS0Egx0qQwMHwa7O35w5p6Wb3jLw7MutAXYHirIAHrpI/EuHetXBu78kKLeMYNsqrolbXb2QVqfIi1SjM8qUw3K5D/mtUEsW6UrWF+Pi2/AAACOHivTJrnqyi4U4kno+0hxIdQSest68VqnEyFiBbxXaF5cF9xMLgkFoWdiBD7zBvFfJNTKGnspsDElR/jxJsoHUV3s5RCGc2ZqhPfSJTW7c9s2+Ro8BgTPY5jlO7V7Scoa7oDXCCABdNlMJqpvPnWaONP7qsfnokVrmTxcMN850SWZolFftpgVcRtNF7wTOkJPwezx3BtvPeRob+XJ17UN35lIoq8csZvM/gg4XXSepgXK9cP3LqnlxN9jUdWnJs2r2eiBYrK5/Iu2S0d6TW7QmDqPS8jUBu/iBb4Y1/nPK4qjAqmufDA67pFaiKHh3miP6ZflbUZ0dt0Ng/znZHXVw0OEtZVy/IFoOwdXVgvWIknRWp/dDXPEZ1W7ZjDkTopp35jx+PFAHdCoUC+x8OvcvhynFzUZ0Swu7k7eOTNlrCiuNBcGrSyKfnZGxTKGpFRruCDLLcDh1GnPsYOt1henWHLDqTYoPzZcsSb8hYBMbiiuxI6N5Kgiqoo0fpienArpv1mUsd72QxaL6Yu90ZFuHmtxzLl/VhB+DCRrH1bGrKbTYrNVz6+hy3fmwlYPlI3MXXJNl1Xc2D8oPUB3DvGved/8JtxQ3YURtG/Vad8UtHK1NWf4mi1xyYWVGGuq/mzJOxf2SGS/8P35wXgV+ddeKSgU8D/83WtgFqidftqpZ5jTR9zGqQjqkV2jYv/G5jiDM+cUnA2VCgVBvBVW/pYG2qVcgO67F1xwtHQMeUEJ5CgVbRRGcAuP05rJ2nRQuOmdiN3Vu0Po/+gt8DE2OKOMWfFoWEj5m91wYhJn5BZqrxkG+vQNlJ9xzWolsrm56nUIWSYb6RcRN3ffmYMaW/PFGk4J3pm0EO43A9wHo4uQgAWMjYorydS+M6jrMDkFOOHNocmXw8jTMdwxWNIBvmtb4leqLUq6lym8AnjvXz6qa/wUS8Gz5JOUf1NP+kjF7FvbWt2BMvyKgHc2zW4ivLTfkS7O45BeOJ1bO+EmcXeFnsXRXZHCba5Z9/PRTRv3mJgITlpAcscmGura5NnpQjuuUWNGQ1XePL46oQp0FlBVKH8Q4+hlJQc/QOcI3JVJb4zcp8qhyxoMVfryjJgoWyz8joQ30szUY3I=,iv:NetbIPB5AeJ0aiiS7wDfAvgWy3Zzfx90A9d7iY8fYP0=,tag:NNSk0PKSwGPx9wq+R+RHyQ==,type:str]
sops:
    lastmodified: "2026-04-09T17:37:40Z"
    mac: ENC[AES256_GCM,data:jER03G0nBXF67/x9tOCDwsKMPNp5vAcYZNbba6Zxho4umlOA4Go7f7Ow4UatgWpEQ3G7XsWp0sSDxAdJFnsFjx3agsJ3XzI4Z/MbQdzA/DZkOnmjGb0DPSOhds/RSlNZOi1Tx5hit1vXzx5IwitzKIFqggaMrefM/ea1/xvpIG0=,iv:m/QG+XQnwdBjmtSB5pcB8nKrME6xtmfcNtX0yVjYSks=,tag:ziooEdVCxifyFuanMvBSEg==,type:str]
    pgp:
        - created_at: "2026-04-09T17:37:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdABF6lYXfivTm8g5nSg6CHFmeXTcocMz2/v7qoIoPRyFIw
            QKJZkTEvGf9swOPlikQslbEj6ooi5opgh5D4zZPsSoZjH6lc9M79fqTL0I1VTcOe
            0l4BjoeQFenWZCBu9arTxAtnbqudeLvz4rh9zrKvtqDNE/rn4S26rGZ7F9YyjIO7
            MId8lITb1YKSL6pu9EBgMB+rojEggYLCgVuspgZGtvX1/qruFqi/cgGRG7Hwn1Jy
            =fkuG
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
