apiVersion: v1
kind: Secret
metadata:
    name: cluster-key
    namespace: openshift-gitops
data:
    sops.asc: ENC[AES256_GCM,data:G5yYGt9Wg0ZTTChqkJGAY/354joh0zCtv/guzBjbMbWyA1nhJNSsrnCeWa16gAPmwKy4TyKttz587NTUa/frLPjwVp9JQRsOyjf4eiTNycAlhGaSQBHV8zdYDe3qy9g53GAJJF0bB09fkjamT8F/0oY2AjRM5DYMoiQIMHU0c9RNRwtiCMAcIg8BXhFqk6GozC5TtZWlAlHVGg8GnJjhdUxjNDglekEc/iL91XFyXffSiocTKLKsawYrujDTKBPaoOTpM9mkECd8es7ZCG9J6y0uCS0cW4culGx2IZ1BkYNwzWzh97FbWYXsX81xkAK43x/XH+JA+chziIHKft3tIaZAgl2MqjHzlURw0PMtvp0cKMmVGUrE8844NNVsI71Cl08Mq0K58lJZM5b+erfKrz+PKTXQ2IxyAMR3SNkl7cTnxg2vhVb3ftVggSGDvRpUa05vBSwwMwklBXwjmD7+lYUYSmMdn8hx54rINKPEOi0uhKYNcV6EYsxcZ9L12sTkRZa88fxuJZ8zZj1Xv3wSPF0iRncvVD5k/0dbUtFQ3P7Xefrb1kikrq1JyeJZTCIYjVwsZh5p/Cga+5zHm7y68KK9+hAXfSDdX8s8a/9RH3DdAKg27IkLk5WxMlpkmW4lWADm4pLNR6tkMh8eN3x3TZ9ip0EO3poi6luFPuvDx0kwKgbBL3n0ycYnuLkPRstqQuSVmud2rKBk5MNpLel/dCJKNpg4PeZz4AoeMVki1kPAhz5typ4HATbO7p0WX4H4xNT2Rx1lbgABpPJ4IBworkoNT43uQbDTmDRE320HnzhpoaNVc9qpLzu3YdL771XWxX54/7FVezjxwdOa+SX7lLUNonymdhLYkxgxMDMuSYeBi7kQudYzwJ3bvYRrevYF1bBxNOgPksSzBXEQ3YvToTsuvkVQnH/RKyWFirJHtTLhSvqiEPL/wbDG3RYlowykgCvqnu+Hv8xUFCTXDNG8ayfQk0nv8MKQcMyasAfpZ2ZASUJnSHQC13I4w83YODND5ITMTJ5bTfaGrS6GU9Oypg9GK0vjOlOOQPBYDs5TNLIPHnhvLsrUGz+57W22Mnzq8H6VNy/QyYXdNe+IVFyBBaSPe/gnyYZdkmP19SshhlxpeXEcHIWM7duYKnw6Aq1kbtMXI7STImmN4UuwwwvmpluFa68PskQ36lZMIqq/oFCnnb/KU5WhiBb+1MK/6oMYVbG7aI8aKi9/x/3gIBuaCWWIZRWJfnlqL8TmzhLZov3wW6om1AJ/SzE6erKUmYbUumY9JS4qZb9sdTBIzl2sy3epbfU=,iv:K3WePROsqhNHkKaAnvNqoa3IGApTtfi9gijAzXfDghE=,tag:esuIih5wqLmls9e45qhpSQ==,type:str]
sops:
    lastmodified: "2026-03-18T16:32:58Z"
    mac: ENC[AES256_GCM,data:ceYxkf+/LQxup8BdiUkkJyzW3nI7SdqBHmx0v7q/9UKQylYtz+U3bwp0v/jpL092kOQBtJEcjkL0/mtjLXEtQPjNQH6gUwC8WLUDIOQrPAcL6qp+Wqen3/Y9fxGDp6H/PPqvusYsLBoA2YquhMrDmsUPxD6t1yDVtQkvieMVjFQ=,iv:j995p68kVGx45lMR9zaDSH+rW/ncdCvEgXqm2BJjKTM=,tag:DPQ1NBGJfHmXxJSWonsvbg==,type:str]
    pgp:
        - created_at: "2026-03-18T16:32:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdA6/5CLzseMzAvaSz1imUIVNyq4KwaaKd1LY8FwBZXdxEw
            sPI+QbTExhPgP56bsPZorFzBQFZh8gg0FEUN5wZNxK9ZmTf+MqgisNAAMYvDQDCA
            0l4BLi/R77RFBhMHLtW1qVgs89aQZjbryIMRnnPzDtmnrEOs5kjfmenpfQFAcp4z
            4NG/bNoE/8duWoinosx+Da36+BVORBhWgORszcIVT7+b9IZHegMD8yWWOVUeM4qo
            =m2Tk
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
