apiVersion: v1
kind: Secret
metadata:
    name: cluster-key
    namespace: openshift-gitops
data:
    sops.asc: ENC[AES256_GCM,data:eFfV9xeyjhdTMqmgclHkpVm8PAW7BFH5aMF4GcDV21EtKDirSjulZH89llElgb7QXxsQ+88K4mOEtI5RmTjtRAt9712Osw/2TUclMn5hMMioNeS07HFaCObJblBL9r+yhokAzQyqrFpE6F5LQ3Le7uqF2HT6l/97PE9mMm3/LMzb4W+wpfQaSl01dP4J7aFsMFYBINEHs41Z1zvY/igOa+Exdm6Io+2KxLEome+t9J464sNDtOAFuZ6cVQXRCr/KJIX6AA13i/ZDOxVNP1srT8LwO7aLgxcvShaylPR1mWnhhT0yg6sBsBT276/hJGXrkvcsxKEroDdqiDA0zAzC3GJUopFoJEDiP+LSJ41kVUG/vDZyjUIghP3k9MK0PhMYLBcgxCVqZwjW/oHRAjPKRx/7/gKOhiwAGENVCNVJBepo3VVUK8xlcGLsw9hji58vxF/J2/YaNTbUaTUoqa49SmFxKGRSAYsg9EdQgSAPUpVM9Jy8TrT/wRDB03HejqektRmKw53pRnnNvYKmjG5bIrcvj1ASZaRVZd3dNWdsW1v4XlXNSp6zO4ibHXzIuxtsJqOUGurFFmoYfTKOQv3rQOvn9xQ55WlLUipPEeoNUYRJya5L8mT3ilCKq8DC3vZkhwh8I4DJY/c+ZnfxJebEjK0NLXlGuwtQMcVycWYpzOXgm+jhQ+1pJseG7k0pUuyuPQJ0ndi/d6uJhwXoBCMFRcbemE4jAN0uJogG6cesGoU5oDfhKBTb68MMjL91epJME42QEXl5cTR+8OMh/+I5UpbHVms9KsoYbEjnV/9j4pav69f0C7IWPJs2DTKOGNQtMehPDVQBz1y3Q3kZ9BQzzq0nJEJIukLvL/3EqQggQxUiOERwX0nVGBHCE4DDv8nX/foE7mxBNYONuPrlcOI+g6OpDLLBDYgVvq0SiZz+N0/NLxAmfCjaQU8XPljEkGt5yW/LNDS3l68jJmsWekMeP8WJX15DdwSJSMhgOEM0JGCapXJ5c8DdtTmSHOIgpGPRkWld7/QempCF5dhm5GTpO4Z3g6nSEj01G+Y1xRuyTk2RRdyAXfVH0/J6wM1rbnOoEeQrQIGh0VZ5PzGiE3usMX3WjdogpQrdEW/qx+PWRoA1BfKyw+ISnk3KOrMLC+yFCdCNqNDyoufk+qRlGBDrY1PqyK0Cqw5x3b0K/fMkXqIEVTIgKWwge3bOyhcXkHFo6tw7t+oFQ/24+1xIvgYF77/NEGZ1jX6KZ0X9PiIAcdb6FDlpiT8uCSeFm5+HCLeVkoOgjr7zskqW+NhgWk1YPsjTFXg=,iv:5dc5A05vPU3A7WZQZHK2eHh3k1knHLilNyHEwm+VAEk=,tag:VDNrp6a4lNDimvJcz64QRg==,type:str]
sops:
    lastmodified: "2026-04-09T18:29:10Z"
    mac: ENC[AES256_GCM,data:lJnI/4Fz1+gPxC1Izy+BFmBUdebxEdR5IGEDVH4uA60SJBg8/DVeYnxxwk41ql5y8PsvZk3XnR3WK0Vy0b5OmCorbasA8IH1Xkiq/9bOr+ciuSR2wUnzeyd0MKTLFxCOe6B8f+3lTTZ7QRK9VrOtSiI8s2E9O+Cv9vfGGQGfneI=,iv:ndEBtMEW3qMon8xf4a1j6AJip+Xv96abqGxYMCo92FQ=,tag:ZFoDHLd+5Fq8fWPvMrdg2Q==,type:str]
    pgp:
        - created_at: "2026-04-09T18:29:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAqRVp1sC9aAQWQ47zzfcTiMe4QOnLgTsuXzCgy+Wt/3sw
            F46Yud7IFG5e5lVaF5eUOYVE6c4LWk76O1S0kIX53n1c/dInzUQkqwV+FgeeNbg4
            0l4BJe6rTTgRS/xM1maJNmNYMqM2oPyd9N9YZfFr6q1FALjmWlu7JKwDL51eYYoA
            mey6Hgr4ShCT9zqBaf5Gdpaz3WS+S4nzCi34PzEB1sSfDVDd3v/+pOhDwqaCrNtT
            =PAeA
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
