apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: cluster
  namespace: openshift-multicluster-engine
spec:
  clusterName: patch-me
  clusterNamespace: openshift-multicluster-engine
  clusterLabels:
    cloud: gcp
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  policyController: 
    enabled: true
  searchCollector:
    enabled: true
